version: "3.7"
services:
  
  db:
    container_name: db
    image: surrealdb/surrealdb:latest
    ports:
      - "5432:8000"
    volumes:
      - ./data:/data
    command: start file:/data/surrealdb.db
    networks:
      - surrealdb
    
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app 
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - surrealdb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  mistral:
    container_name: mistral
    image: ghcr.io/mistralai/mistral-src/vllm:latest
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    command: --host 0.0.0.0 --model mistralai/Mistral-7B-Instruct-v0.2
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - surrealdb


  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - surrealdb

networks:
  surrealdb:
    driver: bridge

    