version: "3.7"
services:
  
  db:
    container_name: db
    build: 
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?authSource=admin
    ports:
      - "5432:5432"
    volumes:
      - ~/.data:/var/lib/postgresql/data
      #- ./db_hba.conf:/var/lib/postgresql/data/db_hba.conf

    networks:
      - main

  mistral:
    container_name: mistral
    image: vllm/vllm-openai:latest
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    command: --host 0.0.0.0 --model TheBloke/Mistral-7B-Instruct-v0.2-AWQ   --gpu-memory-utilization 0.80  --max-model-len 3072
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    networks:
      - main
    restart: always
    depends_on:
      - db

  queue:
    image: rabbitmq:3.7.7-management
    container_name: queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/.docker/rabbitmq:/var/lib/rabbitmq
    networks:
      - main
    restart: always
    depends_on:
      - db

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ~/.docker/redis:/data
    networks:
      - main
    restart: on-failure
    depends_on:
      - db

  bucket:
    image: minio/minio:latest
    container_name: bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./static:/data
    networks:
      - main 
    restart: always
    command: server /data --console-address ":9001"

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app 
    depends_on:
      - db
      - mistral
    env_file:
      - .env
    networks:
      - main
   
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - mistral
      - db
      - queue
      - redis
      - bucket
    networks:
      - main

networks:
  main:
    driver: bridge

